---
- hosts: all
  become: yes  # Run tasks with sudo

  tasks:
    - name: Fix yum/dnf interruptions (if any)
      shell: yum-complete-transaction --cleanup-only || true
      ignore_errors: yes

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes
      changed_when: false

    - name: Add Docker repository
      yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Install required packages
      yum:
        name:
          - yum-utils
        state: present

    - name: Install Docker CE
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
